# Generated by Django 5.0.6 on 2024-06-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.IntegerField(default=1, verbose_name='Perfil'),
        ),
    ]
