# Generated by Django 5.0.6 on 2024-06-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
