# Generated by Django 5.0.3 on 2024-04-28 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
