# Generated by Django 5.0.4 on 2024-04-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
