# Generated by Django 5.0.3 on 2024-06-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(default=0),
        ),
    ]
