# Generated by Django 5.0.3 on 2024-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresos',
            old_name='precio',
            new_name='total_egresos',
        ),
        migrations.RenameField(
            model_name='ingresos',
            old_name='precio',
            new_name='total_ingresos',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='cedula',
            new_name='cedula_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='fecha',
            new_name='fecha_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='precio',
            new_name='precio_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='sector',
            new_name='sector_venta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='telefono',
            new_name='telefono_venta',
        ),
        migrations.AddField(
            model_name='compra',
            name='rif_cedula_compra',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='compra',
            name='sector_compra',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='compra',
            name='telefono_compra',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
