# Generated by Django 5.0.6 on 2024-06-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_precio_egresos_total_egresos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
    ]
