# Generated by Django 5.0.3 on 2024-06-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_existencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
