# Generated by Django 5.0.6 on 2024-06-18 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
    ]
