# Generated by Django 5.0.3 on 2024-06-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_precio_2_producto_precio_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
