# Generated by Django 5.0.6 on 2024-06-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_3',
        ),
    ]
