# Generated by Django 5.0.6 on 2024-06-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_rename_precio_venta_venta_total_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
